name: fmtc_example
description: The example application for 'flutter_map_tile_caching', showcasing
  it's functionality and use-cases.
publish_to: "none"

version: 8.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.4"

dependencies:
  badges: ^3.1.2
  better_open_file: ^3.6.4
  flutter:
    sdk: flutter
  flutter_foreground_task: ^6.1.2
  flutter_map: ^6.1.0
  flutter_map_tile_caching:
  flutter_speed_dial: ^7.0.0
  fmtc_plus_background_downloading: ^8.0.0
  fmtc_plus_sharing: ^8.0.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.0
  osm_nominatim: ^3.0.0
  path: ^1.9.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  stream_transform: ^2.1.0
  validators: ^3.0.0
  version: ^3.0.2

dev_dependencies: null

dependency_overrides:
  flutter_map_tile_caching:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - currentAppVersion.txt
