name: flutter_map_tile_caching
description: Plugin for 'flutter_map' providing advanced caching functionality,
  with ability to download map regions for offline use.
version: 8.0.1
repository: https://github.com/JaffaKetchup/flutter_map_tile_caching
issue_tracker: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues
documentation: https://fmtc.jaffaketchup.dev

funding:
  - https://github.com/sponsors/JaffaKetchup

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.4"

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  http: ^1.1.2
  http_plus: ^0.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  latlong2: ^0.9.0
  meta: ^1.10.0
  path: ^1.9.0
  path_provider: ^2.1.1
  queue: ^3.1.0+2
  stream_transform: ^2.1.0
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1

flutter: null
